language: node_js

node_js:
- '8.0'

branches:
  only:
  - master

sudo: required

addons:
  chrome: stable

befote_install:
- npm install -g yarn@latest

install:
- yarn

script:
- yarn test:coveralls
